"""Initial schema

Revision ID: e2770135f836
Revises: 
Create Date: 2025-06-09 06:13:09.158691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2770135f836'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ehr_files', sa.Column('record_id', sa.String(length=255), nullable=False))
    op.add_column('ehr_files', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.alter_column('ehr_files', 's3_key',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.alter_column('ehr_files', 'policy',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('ehr_files', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index('idx_ehr_files_policy_gin', table_name='ehr_files', postgresql_using='gin')
    op.drop_index('idx_filename', table_name='ehr_files')
    op.drop_index('idx_owner_id', table_name='ehr_files')
    op.create_unique_constraint(None, 'ehr_files', ['record_id'])
    op.drop_constraint('ehr_files_owner_id_fkey', 'ehr_files', type_='foreignkey')
    op.drop_column('ehr_files', 'uploaded_at')
    op.drop_column('users', 'sk_downloaded')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sk_downloaded', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('ehr_files', sa.Column('uploaded_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True))
    op.create_foreign_key('ehr_files_owner_id_fkey', 'ehr_files', 'users', ['owner_id'], ['id'])
    op.drop_constraint(None, 'ehr_files', type_='unique')
    op.create_index('idx_owner_id', 'ehr_files', ['owner_id'], unique=False)
    op.create_index('idx_filename', 'ehr_files', ['filename'], unique=False)
    op.create_index('idx_ehr_files_policy_gin', 'ehr_files', ['policy'], unique=False, postgresql_using='gin')
    op.alter_column('ehr_files', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ehr_files', 'policy',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('ehr_files', 's3_key',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('ehr_files', 'created_at')
    op.drop_column('ehr_files', 'record_id')
    # ### end Alembic commands ###
